// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CardInput = { cardholderName: string | null, brand: string | null, number: string | null, expMonth: string | null, expYear: string | null, code: string | null, };
