// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CardDetail = { cardholderName: string | null, brand: string | null, 
/**
 * Card number + CVV are fetched on demand (`reveal_field(id, "cardNumber"
 * | "cardCode")`); only their presence is sent eagerly.
 */
hasNumber: boolean, expMonth: string | null, expYear: string | null, hasCode: boolean, };
