// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardInput } from "./CardInput";
import type { IdentityInput } from "./IdentityInput";
import type { LoginInput } from "./LoginInput";
import type { SshKeyInput } from "./SshKeyInput";

export type CipherCreateInput = { name: string, folderId: string | null, favorite: boolean, notes: string | null, login: LoginInput | null, card: CardInput | null, identity: IdentityInput | null, sshKey: SshKeyInput | null, 
/**
 * Discriminator chosen by the UI. Accepted values: 1 (Login),
 * 2 (SecureNote), 3 (Card), 4 (Identity), 5 (SshKey).
 */
cipherType: number, 
/**
 * When set, the cipher is created inside the named organization and
 * gets encrypted with the matching org key instead of the user key.
 * Ignored on personal items.
 */
organizationId: string | null, 
/**
 * Collection(s) the cipher should live in when it belongs to an
 * organization.  Ignored when `organization_id` is `None`.
 */
collectionIds: Array<string>, };
