// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttachmentDetail } from "./AttachmentDetail";
import type { CardDetail } from "./CardDetail";
import type { CustomFieldDetail } from "./CustomFieldDetail";
import type { IdentityDetail } from "./IdentityDetail";
import type { LoginDetail } from "./LoginDetail";
import type { SshKeyDetail } from "./SshKeyDetail";

export type CipherDetail = { id: string, kind: number, name: string, notes: string | null, organizationId: string | null, folderId: string | null, collectionIds: Array<string>, revisionDate: string | null, favorite: boolean, login: LoginDetail | null, card: CardDetail | null, identity: IdentityDetail | null, sshKey: SshKeyDetail | null, 
/**
 * Custom fields, in vault order. Hidden ones carry no value — same
 * rule as every other secret (see `reveal_field("custom:<index>")`).
 */
fields: Array<CustomFieldDetail>, 
/**
 * How many past passwords the item carries. The passwords themselves
 * come from `password_history`, on demand.
 */
passwordHistoryCount: number, attachments: Array<AttachmentDetail>, 
/**
 * Whether the item asks for the master password before revealing.
 */
reprompt: boolean, };
