// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardDetail } from "./CardDetail";
import type { IdentityDetail } from "./IdentityDetail";
import type { LoginDetail } from "./LoginDetail";
import type { SshKeyDetail } from "./SshKeyDetail";

export type CipherDetail = { id: string, kind: number, name: string, notes: string | null, organizationId: string | null, folderId: string | null, collectionIds: Array<string>, revisionDate: string | null, favorite: boolean, login: LoginDetail | null, card: CardDetail | null, identity: IdentityDetail | null, sshKey: SshKeyDetail | null, };
