// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CustomFieldInput = { 
/**
 * 0 text, 1 hidden, 2 boolean, 3 linked.
 */
kind: number, name: string | null, value: string | null, 
/**
 * Only meaningful for linked fields (kind 3); echoed back untouched
 * so an item edited here keeps a link another client set up.
 */
linkedId: number | null, };
