// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IdentityInput = { title: string | null, firstName: string | null, middleName: string | null, lastName: string | null, address1: string | null, address2: string | null, address3: string | null, city: string | null, state: string | null, postalCode: string | null, country: string | null, company: string | null, email: string | null, phone: string | null, ssn: string | null, username: string | null, passportNumber: string | null, licenseNumber: string | null, };
