// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LoginInput = { username: string | null, password: string | null, uris: Array<string>, totp: string | null, };
