// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoginOk } from "./LoginOk";
import type { TwoFactorProvider } from "./TwoFactorProvider";

/**
 * IPC-facing variant of `LoginResult` — same shape as the old type, minus
 * the `TokenSet` payload that has no business reaching the WebView.
 */
export type LoginOutcome = { "type": "success", "data": LoginOk } | { "type": "twoFactorRequired", "data": { providers: Array<TwoFactorProvider>, webauthnChallenge?: string, } };
