// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionOrigin } from "./SessionOrigin";

/**
 * Public payload returned to the frontend on a successful login/unlock.
 * Intentionally token-free: the access/refresh tokens and the user key
 * stay inside the Rust `AppState` and never cross the IPC boundary.
 */
export type LoginOk = { email: string, 
/**
 * How this vault was opened. Anything other than `server` means
 * the session is read-only, and the UI says so rather than letting
 * the user discover it by having a save rejected.
 */
origin: SessionOrigin, };
